Repository Im-postor/impostor, pull requests merged in 2022-10, with the labels that each got.

#11 Create Sorting
  Sorting
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#15 Create helicopter.cpp
  C++/Helicopter/helicopter.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#19 Sudoku in java
  JAVA/Sudoku.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#20 Clock in java
  JAVA/clock.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#21 Currency converter in java
  JAVA/currencyConverter.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#22 Create snek.py
  PYTHON/snek.py
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#23 Calculator in java
  JAVA/calculator.java
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#24 Create snake.c
  C/snake.c
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#25 Create TicTacToe.c
  C/TicTacToe.c
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#26 Create Calendar.c
  C/Calendar.c
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#27 Create 2048.c
  C/2048.c
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#28 Create Dino.cpp
  C++/Dino/Dino.cpp
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#30 Add files via upload
  bank management system.c.txt
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#31 Add files via upload
  COVID_19.cpp
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#40 Create strong.c
  strong.c
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#41 Create strong.py
  strong.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#42 Create perfect.go
  perfect.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#43 Armstrong number in c
  C/Armstrong.c
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#44 Palindrome number with C
  C/Palindrome.c
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
